pipeline {
    agent {
        node {
            label 'basha'
        }
    } 



    stages {
        stage('Build') {
            steps{
                echo "hello I am pipeline"

            }
        }
         stage('Test') {
            steps{
                echo "hello I am testing"

            }
        }   
    }
    post{
        always{
            echo "pipelines done"
        }
    }
}