pipeline {
    agent {
        node {
            label 'basha'
        }
    } 
    enviornment{
        course="Devops"
    }



    stages {
        stage('Build') {
            steps{
                script{
                    sh """
                        echo "hello I am building"
                        echo $course
                    """
                }
                

            }
        }
         stage('Test') {
            steps{
                script{
                    sh """
                        echo "hello I am testing"
                    """
                }
            }
        }   
    }
    post{
        always{
            echo "pipelines done"
            cleanWs()
        }
        success {
            echo "pipelines build"
        }
        failure{
            echo "pipelines failed"
        }
    }
}