pipeline {
    agent {
        node {
            label 'Agent'
        }
    } 
    // enviornment {
    //     course="Devops"
    // }
    environment {
        COURSE = "Devops" 
        // this enviornment variables we can in any stage and env also, it will show all the default env 
    }
    options {
        timeout (time: 1 , unit: 'HOURS') 
        // This options function used to set the time limit to our pipeline
    }
    // this parmaters like inputs which we need to give like versions , images
    parameters {
        booleanParam(name: 'Helm push', defaultValue: true, description: 'Toggle this value')
        string(name: 'Api-version', defaultValue: '', description: 'Enter the apiversion')
        booleanParam(name: 'Helm deploy', defaultValue: true, description: 'Toggle this value')
        choice(name: 'CHOICE', choices: ['relase', 'config-branch'], description: 'Pick something')

    }



    stages {
        stage('Build') {
            steps{
                script{
                    sh """
                        echo "hello I am building"
                        echo $COURSE
                        env
                    """
                }
                

            }
        }
         stage('Test') {
            steps{
                script{
                    sh """
                        echo "hello I am testing"
                    """
                }
            }
        }   
    }
    post{
        always{
            echo "pipelines done"
            cleanWs()
        }
        success {
            echo "pipelines build"
        }
        failure{
            echo "pipelines failed"
        }
        aborted {
            echo " pipeline aborted"
        }
    }
}