pipeline {
    node {
        label 'Agent'
    }
    environment {
        COURSE = "Jenkins"
        apiVersion = ""
        ACC_ID = "160885265516"
        PROJECT = "roboshop"
        COMPONENT = "catalogue"
    }
    stages {
        stage{
            steps (Read version) {
                script {
                    def packageJSON = readJSON file: 'package.json'
                    apiversion = packageJSON.version
                    echo "apiVersion is: $apiVersion"
                }
            }
        }
        stage {
            steps {
                script {
                    sh """
                    npm install
                    echo "npm dependencies installed"
                    """
                }

            }
        }
    }
    post {
        always {
            cleanWs()
        }
        success {
            echo "Catalogue pipeline runs successfully"
        }
        failure {
            echo "Catalogue pipeline failed"
        }
        aborted {
            echo "Catalogue pipeline aborted"
        }
    }
}